site: -joyceobi.github.io
title: joyceobi - blog
keywords: 'joyceobi, blog'
description: Joyceobi - Personal blog
lang: en-US
timezone: WAT
repo: 'https://github.com/Joyce-O/-joyceobi.github.io'
google_verify: XXX
google_analytics: UA-XXXXXXXX-00
discus-identifier: XXX
author:
  name: Joyce Obi
  bio: Software Developer <br> Recurser @TheRecurseCenter
  picture: /assets/images/profile.jpg
  github: Joyce-O
  twitter: joyce0bi
  facebook: blank
  instagram: blank
  youtube: 'https://www.youtube.com/channel/UCyak1XSWKXCXweaNvugWxZQ/channels'
  linkedin: joyce-obi
  email: blank
url: ''
baseurl: ''
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: '/page/:num'
collections:
  pages:
    output: true
    permalink: '/:name'
  posts:
    output: true
    permalink: '/:slug'
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
relative_links:
  enabled: true
  collections: false
